name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v4
      # for the private repo comment out if the repo is public
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push Docker image - Crawler
      uses: docker/build-push-action@v2
      with:
        context: ./crawler
        file: ./crawler/Dockerfile
        push: true
        tags: ghcr.io/${{ github.actor }}/portcdm-crawler:${{ github.run_number }}, ghcr.io/${{ github.actor }}/portcdm-crawler:latest

    - name: Build and push Docker image - Notifier
      uses: docker/build-push-action@v2
      with:
        context: ./notifier
        file: ./notifier/Dockerfile
        push: true
        tags: ghcr.io/${{ github.actor }}/portcdm-notifier:${{ github.run_number }}, ghcr.io/${{ github.actor }}/portcdm-notifier:latest
